# Generated by Django 5.0.4 on 2024-06-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_charge', models.CharField(max_length=10)),
                ('service_discription', models.CharField(max_length=500)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_certificate')),
            ],
        ),
    ]
