# Generated by Django 5.0.4 on 2024-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_documents',
        ),
    ]
